racecar:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  

  # Velocity Controllers ---------------------------------------
  left_rear_wheel_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: left_rear_wheel_joint
  right_rear_wheel_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: right_rear_wheel_joint
  left_front_wheel_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: left_front_wheel_joint
  right_front_wheel_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: right_front_wheel_joint


  # Position Controllers ---------------------------------------
  left_steering_hinge_position_controller:
    joint: left_steering_hinge_joint
    type: effort_controllers/JointPositionController
    pid: {p: 100.0, i: 0.0, d: 0.5}
  right_steering_hinge_position_controller:
    joint: right_steering_hinge_joint
    type: effort_controllers/JointPositionController
    pid: {p: 100.0, i: 0.0, d: 0.5}

